# Generated by Django 2.0.3 on 2018-03-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_content',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
