# Generated by Django 2.0.3 on 2018-03-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='posts_number',
        ),
        migrations.AddField(
            model_name='comment',
            name='comments_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
