# Generated by Django 2.0.3 on 2018-03-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180321_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments_number',
        ),
        migrations.AddField(
            model_name='article',
            name='comments_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
