# Generated by Django 2.0.3 on 2018-03-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180322_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
