# Generated by Django 2.0.3 on 2018-03-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180323_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
